name: Terraform Deploy Infra

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Infra Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Create tfvars file
        run: |
          cat > dev.auto.tfvars <<EOF
dockerhub_user     = "${{ secrets.DOCKERHUB_USERNAME }}"
dockerhub_password = "${{ secrets.DOCKERHUB_TOKEN }}"
key_name           = "${{ secrets.EC2_KEY_NAME }}"
environment        = "dev"
EOF

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=dev.auto.tfvars

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=dev.auto.tfvars

      - name: Terraform Outputs
        run: terraform output
