name: Terraform Destroy Infra

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout Infra Repo
        uses: actions/checkout@v4

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      # Step 3: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Step 4: Create tfvars file
      - name: Create tfvars file
        run: |
          cat > dev.auto.tfvars <<EOF
          dockerhub_user     = "${{ secrets.DOCKERHUB_USERNAME }}"
          dockerhub_password = "${{ secrets.DOCKERHUB_TOKEN }}"
          key_name           = "${{ secrets.EC2_KEY_NAME }}"
          environment        = "dev"
          EOF

      # Step 5: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 6: Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file=dev.auto.tfvars
