name: Terraform Destroy

# Allow manual trigger and also on push to a branch if needed
on:
  workflow_dispatch:
  push:
    branches:
      - main # Optional: run on push to main branch

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1 # Change to your region

    steps:
      # Step 1: Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      # Step 3: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 4: Initialize Terraform
      - name: Terraform Init
        working-directory: ./infra # Change to your Terraform directory
        run: terraform init -input=false

      # Step 5: Terraform Destroy
      - name: Terraform Destroy
        working-directory: ./infra # Change to your Terraform directory
        run: terraform destroy -auto-approve
